### ISSUE TITLE
Luigi configuration file should be transpiled

### ISSUE THREAD

**Issue by maxmarkus** [kyma-project/luigi#268]
The `extendedConfiguration.js` is currently written in ES5 and tends to get quite long once you start adding external dependencies. Like business logic for fetching data and transforming it to fit the navigation configuration. 

- find a way to run `npm run start` which transpiles config to separate file with watcher and still doing normal npm run start behavior we currently have.
- with this we sould be able to split the config into multiple files, with classes, helpers and be able to use also node modules inside.
- npm run `build` should also transpile it once

Suggestion for _npm run start_ could be excluding the command to a shell script which spaws a child process for _transpiling and watching_ the config and running the normal _ng serve ..._ command afterwards. Spawning a child process is as simple as `(COMMAND &)`, like `(npm run e2e:open &)`

**Comment by jesusreal** [comment]
I was playing around with this and I found a possible direction. [This file](https://app.zenhub.com/files/139590701/b32256f9-b939-4ec0-957f-e57ffec0fe41/download) includes the proposed angular.json file + npm script to run console app locally. Additionally *console-config.js* script import has to be removed since angular cli is injecting it automatically.

The problem with this approach is that it is not possible to access to consoleapp from luigi app.

**Comment by parostatkiem** [comment]
Don't forget about those `var`s ![image.png](https://images.zenhubusercontent.com/5ba8d87d4e030d642cf5cd1c/66dff602-f8d6-468b-b995-63cc645e4877)
