### ISSUE TITLE
Provide es5 compatible luigi

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#53]
**Description**

Provide es5 compatible versions for :

- client - compile it manually and commit to the repo.
- core - set up target version to es5

**Reasons**

There seem to be interest in having es5 compatible luigi (core and client)

**Comment by kwiatekus** [comment]
@y-kkamil :

> there's no need to change anything in core - apparently babel compiles code to es5 implicitly

**Comment by kwiatekus** [comment]
@y-kkamil :

> I have created UMD for client lib, as defined in https://github.com/umdjs/umd
> which means that client will be available with node's require, regular import statement and also as a global object

**Comment by kwiatekus** [comment]
https://github.com/kyma-project/luigi/pull/33

**Comment by y-kkamil** [comment]
* added babel-polyfill to support es6+ features in core.
* added polyfills.js file to enable support for some DOM functionalities we make use of in core (.prepend() method, onhashchange newURL/oldURL properties) that IE 11 lacks. (they are not covered by babel-polyfill)
* not a perfect solution, though - every time one makes use of something that is not supported, he has to add the polyfill to polyfill.js

luigi-sample-angular related:
* also, luigi-sample-angular won't work out-of-box. IE-relevant lines of code have to be uncommented in polyfills.ts file before running it. should we document that somehow?
* even with all these polyfills in place app still crashes somehow with:
`Uncaught (in promise): TypeError: Unable to get property 'instance' of undefined or null reference`
 seems to be an angular related problem

**Comment by y-kkamil** [comment]
this needs to be investigated further. how to support ie 11 with as less pain as possible ;)
* how to polyfill missing DOM features?
* is there a library, that can do it for us, instead of manually adding polyfills?
* https://www.npmjs.com/package/fix-ie might be a solution
* how to load these polyfills 'on-demand', only for IE, to avoid excess data transfer when using other browsers? (https://stackoverflow.com/questions/29987969/how-to-load-a-script-only-in-ie <-- this might be of some help), maybe there are some webpack plugins?
* maybe https://polyfill.io would be a solution?
* would then babel-polyfill be needed? (it already surged our bundle size)

**Comment by y-kkamil** [comment]
there's a closed PR, that might be worth checking with a basic solution:
https://github.com/kyma-project/luigi/pull/98
