### ISSUE TITLE
fundamental-ui css is not bundled properly after following application setup steps

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#69]
**Description**

[The script demonstrating application setup for angular 6](https://github.com/kyma-project/luigi/blob/master/docs/application-setup.md#application-setup-for-angular-6) doesn't include proper bundling of fundamental-ui.

**Actual result**

When you follow the application setup, the css from fundamental ui will not be properly bundled and would not be available for index.html to import using href `/fundamental-ui/fundamental-ui.min.css`:

 `Refused to apply style from 'http://localhost:4200/fundamental-ui/fundamental-ui.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Solution proposal**

Define additional steps in the script that would assure additional asset entry in angular.json file
I.e:
```
{
                "glob": "**",
                "input": "node_modules/fundamental-ui/dist",
                "output": "/fundamental-ui"
              }
```

**Comment by jesusreal** [comment]
This issue has been solved by just adding some more content to angular.json file through terminal command, but I identified an underlying issue which is the following: 

As part of this task affecting the angular example, I questioned why we need to import fundamental-ui.min.css file in luigi app html. Luigi should satisfy its own dependencies by itself, without the need of any app using Luigi to do that. Therefore, if an app using Luigi has fundamental-ui as a dependency (as our angular example does), this dependency should be used exclusively for the angular app (microfrontend), and under no circumstance by Luigi.

The actual issue is that *when Luigi core is bundled, fonts are not properly loaded, including icon fonts*. As a consequence, our angular example needs to provide Luigi with them by first importing luigi.min.scss in luigi app html

`  <link rel='stylesheet' href='/fundamental-ui/fundamental-ui.min.css'>
`

and second by making fonts and icons available to fundamental-ui.min.scss via the angular app build pipeline

```  
{
  "glob": "fundamental-ui.min.css",
  "input": "node_modules/fundamental-ui/dist",
  "output": "/fundamental-ui"
},
{
  "glob": "fonts/**",
  "input": "node_modules/fundamental-ui/dist",
  "output": "/fundamental-ui"
},
{
  "glob": "SAP-icons.*",
  "input": "node_modules/fundamental-ui/dist",
  "output": "/fundamental-ui"
},
```

*We don't want every user to add this code to their apps using Luigi*, this is a hack imho.

Another drawback of this configuration is that Luigi core uses internally its own dependency of fundamental-ui, while in the angular example app we are supplying Luigi with extra content from fundamental-ui by using example´s own dependency of fundamental-ui. A mismatch of versions between both copies from fundamental-ui might lead to issues.

I tried to solved the issue, but failed.

In Luigi core build pipeline, our Svelte loader preprocess handler is properly processing the @font-face at-rule, but in the generated luigi.css file all the occurrences of @font-face are empty objects. Most likely the paths of the url property are wrongly referenced, but I reasoned about that and tried different combinations without succeeding. Most likely, as a consequence of using the wrong paths, fonts and icons files are not being copied to the core public folder.

Therefore, I am providing a solution for the current issue, but none for the underlying issue.

I will bring this topic to internal discussion before putting any additional effort on it.
